name: my_demo_workflow

on:
    schedule:
    - cron:  '*/5 * * * *'

jobs:
  demo_job:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout current repository
        uses: actions/checkout@v2

      - name: Set up Python 3.7
        uses: actions/setup-python@v1
        with:
          python-version: 3.7

      - name: Install requirements
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Generate output files
        run: |
          cd subprogram
          python subprogram.py
          cd ..
          python program.py

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v2
        with:
            base: master
            branch: output-files-update
            branch-suffix: timestamp
            commit_message: "feat: update output files"
            committer: Javier López <javierlopez@uc.cl>
            title: "Output files updated"
            body: "Output files generated by subprogram and, then, by program where updated."
            author: Javier López <javierlopez@uc.cl>
